name: IndoCafe CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # JOB 1: Test the Backend
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server # Tell GitHub to look inside 'server' folder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install Dependencies
        run: npm install

      # This is the "Gatekeeper". If your code has syntax errors, this fails.
      - name: Check for Syntax Errors (Dry Run)
        run: node --check index.js

  # JOB 2: Test the Frontend
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Verify Build
        run: npm run build # If React fails to build, the pipeline stops here.

  # JOB 3: Deploy to Render (Only if Job 1 passes)
  deploy-backend:
    needs: [build-backend] # Wait for backend tests to pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy if we are on the main branch

    steps:
      - name: Trigger Render Deployment
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"
